[theme]
base = "light"
primaryColor = "#1f77b4"  # Cor primária opcional (azul claro)
backgroundColor = "#ffffff"  # Fundo branco
secondaryBackgroundColor = "#f0f2f6"  # Fundo secundário claro
textColor = "#262730"  # Texto escuro para contraste
